name: app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  animations: ^2.0.2
  badges: ^2.0.2
  cloud_firestore: ^3.1.15
  connectivity_plus: ^2.2.1
  cupertino_icons: ^1.0.2
  curved_navigation_bar: ^1.0.3
  equatable: ^2.0.3
  firebase_analytics: ^9.1.8
  firebase_auth: ^3.3.18
  firebase_core: ^1.17.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.2+1
  flutter_native_splash: ^2.1.1
  freezed_annotation: ^1.1.0
  geolocator: ^8.2.0
  glassmorphism: null
  go_router: ^3.0.4
  google_fonts: ^2.3.1
  hooks_riverpod: ^1.0.3
  json_annotation: ^4.4.0
  local_auth: ^1.1.11
  mockito: ^5.1.0
  mocktail: ^0.3.0
  uuid: ^3.0.6

dev_dependencies:
  build_runner: ^2.1.8
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  freezed: ">=1.0.0 <1.1.1"
  json_serializable: ^6.1.5

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    #  - family: Allura
    #    fonts:
    #      - asset: lib\src\config\font_families\Allura\Allura-Regular.ttf
    #  - family: Codystar
    #    fonts:
    #      - asset: lib\src\config\font_families\Codystar\Codystar-Regular.ttf
    #  - family: Hachi_Maru_Pop
    #    fonts:
    #      - asset: lib\src\config\font_families\Hachi_Maru_Pop\HachiMaruPop-Regular.ttf
    #  - family: League_Script
    #    fonts:
    #      - asset: app\lib\src\config\font_families\League_Script\LeagueScript-Regular.ttf
    #  - family: Megrim
    #    fonts:
    #      - asset: lib\src\config\font_families\Megrim\Megrim-Regular.ttf
    #  - family: Pinyon_Script
    #    fonts:
    #      - asset: lib/src/config/font_families/Pinyon_Script/PinyonScript-Regular.ttf
    #  - family: Neon
    #    fonts:
    #  - asset: lib\src\config\font_families\Neon\neon.ttf
    - family: NeonLights
      fonts:
        - asset: lib\src\config\font_families\neonlights.ttf
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
